// AUTO-GENERATED from dashboard_automatique_complete_FINAL_18_03_graphs.xlsx

class Bureau {
  final String commune, arrondissement, nomCentre, nomBureau;
  final int numeroCentre, votants;
  const Bureau({required this.commune, required this.arrondissement, required this.nomCentre, required this.nomBureau, required this.numeroCentre, required this.votants});
}

class CentreSuivi {
  final String commune, arrondissement, nomCentre;
  final int codeCentre, nombreBureaux, inscrits, cumulRetraits, restant;
  final double pctRetrait;
  final Map<String, int> retraitsDailyData;
  const CentreSuivi({required this.commune, required this.arrondissement, required this.nomCentre, required this.codeCentre, required this.nombreBureaux, required this.inscrits, required this.cumulRetraits, required this.restant, required this.pctRetrait, required this.retraitsDailyData});
}

class SyntheseArr {
  final String arrondissement;
  final int inscrits, retires, restant;
  final double pctRetrait;
  const SyntheseArr({required this.arrondissement, required this.inscrits, required this.retires, required this.restant, required this.pctRetrait});
}

class ElectionData {
  static const List<Bureau> bureaux = [
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'PREFECTURE DE DJIBOUTI', nomBureau: 'PREFECTURE DE DJIBOUTI 1', numeroCentre: 1, votants: 311),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'PREFECTURE DE DJIBOUTI', nomBureau: 'PREFECTURE DE DJIBOUTI 2', numeroCentre: 2, votants: 311),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'PREFECTURE DE DJIBOUTI', nomBureau: 'PREFECTURE DE DJIBOUTI 3', numeroCentre: 3, votants: 312),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -1', numeroCentre: 4, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -2', numeroCentre: 5, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -3', numeroCentre: 6, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -4', numeroCentre: 7, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -5', numeroCentre: 8, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -6', numeroCentre: 9, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -7', numeroCentre: 10, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -8', numeroCentre: 11, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -9', numeroCentre: 12, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -10', numeroCentre: 13, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -11', numeroCentre: 14, votants: 395),
    Bureau(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', nomBureau: 'ECOLE Z.P.S -12', numeroCentre: 15, votants: 400),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE HADJI-DIDEH', nomBureau: 'ECOLE HADJI-DIDEH -1', numeroCentre: 16, votants: 383),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE HADJI-DIDEH', nomBureau: 'ECOLE HADJI-DIDEH -2', numeroCentre: 17, votants: 383),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE HADJI-DIDEH', nomBureau: 'ECOLE HADJI-DIDEH -3', numeroCentre: 18, votants: 383),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE HADJI-DIDEH', nomBureau: 'ECOLE HADJI-DIDEH -4', numeroCentre: 19, votants: 383),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE HADJI-DIDEH', nomBureau: 'ECOLE HADJI-DIDEH -5', numeroCentre: 20, votants: 383),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE HADJI-DIDEH', nomBureau: 'ECOLE HADJI-DIDEH -6', numeroCentre: 21, votants: 383),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE HADJI-DIDEH', nomBureau: 'ECOLE HADJI-DIDEH -7', numeroCentre: 22, votants: 383),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE HADJI-DIDEH', nomBureau: 'ECOLE HADJI-DIDEH -8', numeroCentre: 23, votants: 384),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'PREMIER ARRONDT', nomBureau: 'PREMIER ARRONDT -1', numeroCentre: 24, votants: 358),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'PREMIER ARRONDT', nomBureau: 'PREMIER ARRONDT -2', numeroCentre: 25, votants: 358),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'PREMIER ARRONDT', nomBureau: 'PREMIER ARRONDT -3', numeroCentre: 26, votants: 358),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'PREMIER ARRONDT', nomBureau: 'PREMIER ARRONDT -4', numeroCentre: 27, votants: 358),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'PREMIER ARRONDT', nomBureau: 'PREMIER ARRONDT -5', numeroCentre: 28, votants: 358),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CHARIA CENTRALE', nomBureau: 'CHARIA CENTRALE -1', numeroCentre: 29, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CHARIA CENTRALE', nomBureau: 'CHARIA CENTRALE -2', numeroCentre: 30, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CHARIA CENTRALE', nomBureau: 'CHARIA CENTRALE-3', numeroCentre: 31, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CHARIA CENTRALE', nomBureau: 'CHARIA CENTRALE-4', numeroCentre: 32, votants: 410),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 3', nomBureau: 'CDC Quartier 3 -1', numeroCentre: 33, votants: 463),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 3', nomBureau: 'CDC Quartier 3 -2', numeroCentre: 34, votants: 463),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 3', nomBureau: 'CDC Quartier 3 -3', numeroCentre: 35, votants: 463),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 3', nomBureau: 'CDC Quartier 3 -4', numeroCentre: 36, votants: 466),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 3', nomBureau: 'CDC Quartier 3A I -1', numeroCentre: 37, votants: 291),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 3', nomBureau: 'CDC Quartier 3A I -2', numeroCentre: 38, votants: 291),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 3', nomBureau: 'CDC Quartier 3A I -3', numeroCentre: 39, votants: 291),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 3', nomBureau: 'CDC Quartier 3A I -4', numeroCentre: 40, votants: 293),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 4', nomBureau: 'CDC QUARTIER 4 I -1', numeroCentre: 41, votants: 489),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 4', nomBureau: 'CDC QUARTIER 4 I -2', numeroCentre: 42, votants: 489),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 4', nomBureau: 'CDC QUARTIER 4 I -3', numeroCentre: 43, votants: 489),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 4', nomBureau: 'CDC QUARTIER 4 I -4', numeroCentre: 44, votants: 490),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 4', nomBureau: 'CDC QUARTIER 4A I -1', numeroCentre: 45, votants: 316),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 4', nomBureau: 'CDC QUARTIER 4A I -2', numeroCentre: 46, votants: 316),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 4', nomBureau: 'CDC QUARTIER 4A I -3', numeroCentre: 47, votants: 316),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 4', nomBureau: 'CDC QUARTIER 4A I -4', numeroCentre: 48, votants: 316),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'OFFICE VOIRIE DJIBOUTI', nomBureau: 'OVD 1 -1', numeroCentre: 49, votants: 406),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'OFFICE VOIRIE DJIBOUTI', nomBureau: 'OVD 1 -2', numeroCentre: 50, votants: 406),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'OFFICE VOIRIE DJIBOUTI', nomBureau: 'OVD 1 -3', numeroCentre: 51, votants: 406),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'OFFICE VOIRIE DJIBOUTI', nomBureau: 'OVD 1 -4', numeroCentre: 52, votants: 406),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'OFFICE VOIRIE DJIBOUTI', nomBureau: 'OVD 1 -5', numeroCentre: 53, votants: 406),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'OFFICE VOIRIE DJIBOUTI', nomBureau: 'OVD 1 -6', numeroCentre: 54, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -1', numeroCentre: 55, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -2', numeroCentre: 56, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -3', numeroCentre: 57, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -4', numeroCentre: 58, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -5', numeroCentre: 59, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -6', numeroCentre: 60, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -7', numeroCentre: 61, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -8', numeroCentre: 62, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -9', numeroCentre: 63, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -10', numeroCentre: 64, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -11', numeroCentre: 65, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -12', numeroCentre: 66, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -13', numeroCentre: 67, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -14', numeroCentre: 68, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', nomBureau: 'ECOLE EINGUELLA I -15', numeroCentre: 69, votants: 402),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -1', numeroCentre: 70, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -2', numeroCentre: 71, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -3', numeroCentre: 72, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -4', numeroCentre: 73, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -5', numeroCentre: 74, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -6', numeroCentre: 75, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -7', numeroCentre: 76, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -8', numeroCentre: 77, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -9', numeroCentre: 78, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -10', numeroCentre: 79, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', nomBureau: 'ECOLE QUARTIER 5 I -11', numeroCentre: 80, votants: 406),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', nomBureau: 'ECOLE CHATEAU D\'EAU I -1', numeroCentre: 81, votants: 379),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', nomBureau: 'ECOLE CHATEAU D\'EAU I -2', numeroCentre: 82, votants: 379),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', nomBureau: 'ECOLE CHATEAU D\'EAU I -3', numeroCentre: 83, votants: 379),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', nomBureau: 'ECOLE CHATEAU D\'EAU I -4', numeroCentre: 84, votants: 379),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', nomBureau: 'ECOLE CHATEAU D\'EAU I -5', numeroCentre: 85, votants: 379),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', nomBureau: 'ECOLE CHATEAU D\'EAU I -6', numeroCentre: 86, votants: 379),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', nomBureau: 'ECOLE CHATEAU D\'EAU I -7', numeroCentre: 87, votants: 379),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', nomBureau: 'ECOLE CHATEAU D\'EAU I -8', numeroCentre: 88, votants: 379),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', nomBureau: 'ECOLE CHATEAU D\'EAU I -9', numeroCentre: 89, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -1', numeroCentre: 90, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -2', numeroCentre: 91, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -3', numeroCentre: 92, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -4', numeroCentre: 93, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -5', numeroCentre: 94, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -6', numeroCentre: 95, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -7', numeroCentre: 96, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -8', numeroCentre: 97, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -9', numeroCentre: 98, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -10', numeroCentre: 99, votants: 395),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', nomBureau: 'ECOLE QUARTIER 6 BIS I -11', numeroCentre: 100, votants: 401),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -1', numeroCentre: 101, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -2', numeroCentre: 102, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -3', numeroCentre: 103, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -4', numeroCentre: 104, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -5', numeroCentre: 105, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -6', numeroCentre: 106, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -7', numeroCentre: 107, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -8', numeroCentre: 108, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -9', numeroCentre: 109, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -10', numeroCentre: 110, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -11', numeroCentre: 111, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -12', numeroCentre: 112, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -13', numeroCentre: 113, votants: 408),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', nomBureau: 'ECOLE QUARTIER 7 I -14', numeroCentre: 114, votants: 414),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -1', numeroCentre: 115, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -2', numeroCentre: 116, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -3', numeroCentre: 117, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -4', numeroCentre: 118, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -5', numeroCentre: 119, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -6', numeroCentre: 120, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -7', numeroCentre: 121, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -8', numeroCentre: 122, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -9', numeroCentre: 123, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -10', numeroCentre: 124, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -11', numeroCentre: 125, votants: 392),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', nomBureau: 'ECOLE GACHAMALEH I -12', numeroCentre: 126, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -1', numeroCentre: 127, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -2', numeroCentre: 128, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -3', numeroCentre: 129, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -4', numeroCentre: 130, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -5', numeroCentre: 131, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -6', numeroCentre: 132, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -7', numeroCentre: 133, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -8', numeroCentre: 134, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -9', numeroCentre: 135, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -10', numeroCentre: 136, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -11', numeroCentre: 137, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -12', numeroCentre: 138, votants: 394),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', nomBureau: 'ECOLE GUELLEH BATAL I -13', numeroCentre: 139, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-1', numeroCentre: 140, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-2', numeroCentre: 141, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-3', numeroCentre: 142, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-4', numeroCentre: 143, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-5', numeroCentre: 144, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-6', numeroCentre: 145, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-7', numeroCentre: 146, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-8', numeroCentre: 147, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-9', numeroCentre: 148, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-10', numeroCentre: 149, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-11', numeroCentre: 150, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-12', numeroCentre: 151, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-13', numeroCentre: 152, votants: 393),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', nomBureau: 'ECOLE ARHIBA I-14', numeroCentre: 153, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -1', numeroCentre: 154, votants: 398),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -2', numeroCentre: 155, votants: 398),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -3', numeroCentre: 156, votants: 398),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -4', numeroCentre: 157, votants: 398),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -5', numeroCentre: 158, votants: 398),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -6', numeroCentre: 159, votants: 398),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -7', numeroCentre: 160, votants: 398),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -8', numeroCentre: 161, votants: 398),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -9', numeroCentre: 162, votants: 398),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', nomBureau: 'ECOLE AL-HOURIYA I -10', numeroCentre: 163, votants: 403),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE DU STADE', nomBureau: 'ECOLE DU STADE I -1', numeroCentre: 164, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE DU STADE', nomBureau: 'ECOLE DU STADE I -2', numeroCentre: 165, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE DU STADE', nomBureau: 'ECOLE DU STADE I -3', numeroCentre: 166, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE DU STADE', nomBureau: 'ECOLE DU STADE I -4', numeroCentre: 167, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE DU STADE', nomBureau: 'ECOLE DU STADE I -5', numeroCentre: 168, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE DU STADE', nomBureau: 'ECOLE DU STADE I -6', numeroCentre: 169, votants: 397),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE DU STADE', nomBureau: 'ECOLE DU STADE I -7', numeroCentre: 170, votants: 403),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 1', numeroCentre: 171, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 2', numeroCentre: 172, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 3', numeroCentre: 173, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 4', numeroCentre: 174, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 5', numeroCentre: 175, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 6', numeroCentre: 176, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 7', numeroCentre: 177, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 8', numeroCentre: 178, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 9', numeroCentre: 179, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 10', numeroCentre: 180, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 11', numeroCentre: 181, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 12', numeroCentre: 182, votants: 411),
    Bureau(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', nomBureau: 'CEM AMBOULI 13', numeroCentre: 183, votants: 417),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-1', numeroCentre: 184, votants: 409),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-2', numeroCentre: 185, votants: 409),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-3', numeroCentre: 186, votants: 409),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-4', numeroCentre: 187, votants: 409),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-5', numeroCentre: 188, votants: 409),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-6', numeroCentre: 189, votants: 409),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-7', numeroCentre: 190, votants: 409),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-8', numeroCentre: 191, votants: 409),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-9', numeroCentre: 192, votants: 409),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', nomBureau: 'ECOLE AMBOULI I-10', numeroCentre: 193, votants: 412),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-1', numeroCentre: 194, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-2', numeroCentre: 195, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-3', numeroCentre: 196, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-4', numeroCentre: 197, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-5', numeroCentre: 198, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-6', numeroCentre: 199, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-7', numeroCentre: 200, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-8', numeroCentre: 201, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-9', numeroCentre: 202, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-10', numeroCentre: 203, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-11', numeroCentre: 204, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-12', numeroCentre: 205, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-13', numeroCentre: 206, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-14', numeroCentre: 207, votants: 387),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', nomBureau: 'ECOLE AMBOULI II-15', numeroCentre: 208, votants: 401),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', nomBureau: 'ECOLE GABODE V-1', numeroCentre: 209, votants: 374),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', nomBureau: 'ECOLE GABODE V-2', numeroCentre: 210, votants: 374),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', nomBureau: 'ECOLE GABODE V-3', numeroCentre: 211, votants: 374),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', nomBureau: 'ECOLE GABODE V-4', numeroCentre: 212, votants: 374),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', nomBureau: 'ECOLE GABODE V-5', numeroCentre: 213, votants: 374),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', nomBureau: 'ECOLE GABODE V-6', numeroCentre: 214, votants: 374),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', nomBureau: 'ECOLE GABODE V-7', numeroCentre: 215, votants: 374),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', nomBureau: 'ECOLE GABODE V-8', numeroCentre: 216, votants: 374),
    Bureau(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', nomBureau: 'ECOLE GABODE V-9', numeroCentre: 217, votants: 375),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-1', numeroCentre: 218, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-2', numeroCentre: 219, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-3', numeroCentre: 220, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-4', numeroCentre: 221, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-5', numeroCentre: 222, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-6', numeroCentre: 223, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-7', numeroCentre: 224, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-8', numeroCentre: 225, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-9', numeroCentre: 226, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-10', numeroCentre: 227, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-11', numeroCentre: 228, votants: 374),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', nomBureau: 'ECOLE BALBALA I-12', numeroCentre: 229, votants: 384),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -1', numeroCentre: 230, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -2', numeroCentre: 231, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -3', numeroCentre: 232, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -4', numeroCentre: 233, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -5', numeroCentre: 234, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -6', numeroCentre: 235, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -7', numeroCentre: 236, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -8', numeroCentre: 237, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -9', numeroCentre: 238, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -10', numeroCentre: 239, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -11', numeroCentre: 240, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -12', numeroCentre: 241, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -13', numeroCentre: 242, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -14', numeroCentre: 243, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -15', numeroCentre: 244, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -16', numeroCentre: 245, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -17', numeroCentre: 246, votants: 402),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', nomBureau: 'CEM PHARE I -18', numeroCentre: 247, votants: 411),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-1', numeroCentre: 248, votants: 381),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-2', numeroCentre: 249, votants: 381),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-3', numeroCentre: 250, votants: 381),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-4', numeroCentre: 251, votants: 381),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-5', numeroCentre: 252, votants: 381),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-6', numeroCentre: 253, votants: 381),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-7', numeroCentre: 254, votants: 381),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-8', numeroCentre: 255, votants: 381),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-9', numeroCentre: 256, votants: 381),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', nomBureau: 'ECOLE BALBALA II-10', numeroCentre: 257, votants: 386),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', nomBureau: 'CEM HAYEL SAID 1', numeroCentre: 258, votants: 403),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', nomBureau: 'CEM HAYEL SAID 2', numeroCentre: 259, votants: 403),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', nomBureau: 'CEM HAYEL SAID 3', numeroCentre: 260, votants: 403),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', nomBureau: 'CEM HAYEL SAID 4', numeroCentre: 261, votants: 403),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', nomBureau: 'CEM HAYEL SAID 5', numeroCentre: 262, votants: 403),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', nomBureau: 'CEM HAYEL SAID 6', numeroCentre: 263, votants: 403),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', nomBureau: 'CEM HAYEL SAID 7', numeroCentre: 264, votants: 403),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', nomBureau: 'CEM HAYEL SAID 8', numeroCentre: 265, votants: 403),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', nomBureau: 'CEM HAYEL SAID 9', numeroCentre: 266, votants: 410),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA III', nomBureau: 'ECOLE BALBALA III-1', numeroCentre: 267, votants: 416),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA III', nomBureau: 'ECOLE BALBALA III-2', numeroCentre: 268, votants: 416),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA III', nomBureau: 'ECOLE BALBALA III-3', numeroCentre: 269, votants: 416),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA III', nomBureau: 'ECOLE BALBALA III-4', numeroCentre: 270, votants: 416),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA III', nomBureau: 'ECOLE BALBALA III-5', numeroCentre: 271, votants: 416),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA III', nomBureau: 'ECOLE BALBALA III-6', numeroCentre: 272, votants: 416),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA III', nomBureau: 'ECOLE BALBALA III-7', numeroCentre: 273, votants: 416),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA III', nomBureau: 'ECOLE BALBALA III-8', numeroCentre: 274, votants: 418),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-1', numeroCentre: 275, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-2', numeroCentre: 276, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-3', numeroCentre: 277, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-4', numeroCentre: 278, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-5', numeroCentre: 279, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-6', numeroCentre: 280, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-7', numeroCentre: 281, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-8', numeroCentre: 282, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-9', numeroCentre: 283, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-10', numeroCentre: 284, votants: 380),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', nomBureau: 'ECOLE BALBALA VII-11', numeroCentre: 285, votants: 387),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', nomBureau: 'ECOLE BALBALA VII BIS 1', numeroCentre: 286, votants: 412),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', nomBureau: 'ECOLE BALBALA VII BIS 2', numeroCentre: 287, votants: 412),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', nomBureau: 'ECOLE BALBALA VII BIS 3', numeroCentre: 288, votants: 412),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', nomBureau: 'ECOLE BALBALA VII BIS 4', numeroCentre: 289, votants: 412),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', nomBureau: 'ECOLE BALBALA VII BIS 5', numeroCentre: 290, votants: 412),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', nomBureau: 'ECOLE BALBALA VII BIS 6', numeroCentre: 291, votants: 412),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', nomBureau: 'ECOLE BALBALA VII BIS 7', numeroCentre: 292, votants: 412),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', nomBureau: 'ECOLE BALBALA VII BIS 8', numeroCentre: 293, votants: 412),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', nomBureau: 'ECOLE BALBALA VII BIS 9', numeroCentre: 294, votants: 415),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -1', numeroCentre: 295, votants: 378),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -2', numeroCentre: 296, votants: 378),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -3', numeroCentre: 297, votants: 378),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -4', numeroCentre: 298, votants: 378),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -5', numeroCentre: 299, votants: 378),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -6', numeroCentre: 300, votants: 378),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -7', numeroCentre: 301, votants: 378),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -8', numeroCentre: 302, votants: 378),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -9', numeroCentre: 303, votants: 378),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', nomBureau: 'ECOLE PK 12 I -10', numeroCentre: 304, votants: 387),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', nomBureau: 'ECOLE PK 14-1', numeroCentre: 305, votants: 404),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', nomBureau: 'ECOLE PK 14-2', numeroCentre: 306, votants: 404),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', nomBureau: 'ECOLE PK 14-3', numeroCentre: 307, votants: 404),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', nomBureau: 'ECOLE PK 14-4', numeroCentre: 308, votants: 404),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', nomBureau: 'ECOLE PK 14-5', numeroCentre: 309, votants: 404),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', nomBureau: 'ECOLE PK 14-6', numeroCentre: 310, votants: 404),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', nomBureau: 'ECOLE PK 14-7', numeroCentre: 311, votants: 404),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', nomBureau: 'ECOLE PK 14-8', numeroCentre: 312, votants: 404),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', nomBureau: 'ECOLE PK 14-9', numeroCentre: 313, votants: 407),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE NITOBE', nomBureau: 'ECOLE NITOBE 1', numeroCentre: 314, votants: 384),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE NITOBE', nomBureau: 'ECOLE NITOBE 2', numeroCentre: 315, votants: 384),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE NITOBE', nomBureau: 'ECOLE NITOBE 3', numeroCentre: 316, votants: 384),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE NITOBE', nomBureau: 'ECOLE NITOBE 4', numeroCentre: 317, votants: 384),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE NITOBE', nomBureau: 'ECOLE NITOBE 5', numeroCentre: 318, votants: 384),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE NITOBE', nomBureau: 'ECOLE NITOBE 6', numeroCentre: 319, votants: 384),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE NITOBE', nomBureau: 'ECOLE NITOBE 7', numeroCentre: 320, votants: 384),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE NITOBE', nomBureau: 'ECOLE NITOBE 8', numeroCentre: 321, votants: 387),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 20', nomBureau: 'ECOLE PK 20 I -1', numeroCentre: 322, votants: 307),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 20', nomBureau: 'ECOLE PK 20 I -2', numeroCentre: 323, votants: 307),
    Bureau(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 20', nomBureau: 'ECOLE PK 20 I -3', numeroCentre: 324, votants: 308),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-1', numeroCentre: 325, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-2', numeroCentre: 326, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-3', numeroCentre: 327, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-4', numeroCentre: 328, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-5', numeroCentre: 329, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-6', numeroCentre: 330, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-7', numeroCentre: 331, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-8', numeroCentre: 332, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-9', numeroCentre: 333, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-10', numeroCentre: 334, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-11', numeroCentre: 335, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-12', numeroCentre: 336, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-13', numeroCentre: 337, votants: 393),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', nomBureau: 'ECOLE BALBALA VI-14', numeroCentre: 338, votants: 395),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -1', numeroCentre: 339, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -2', numeroCentre: 340, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -3', numeroCentre: 341, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -4', numeroCentre: 342, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -5', numeroCentre: 343, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -6', numeroCentre: 344, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -7', numeroCentre: 345, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -8', numeroCentre: 346, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -9', numeroCentre: 347, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -10', numeroCentre: 348, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -11', numeroCentre: 349, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -12', numeroCentre: 350, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -13', numeroCentre: 351, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -14', numeroCentre: 352, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -15', numeroCentre: 353, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -16', numeroCentre: 354, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -17', numeroCentre: 355, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -18', numeroCentre: 356, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -19', numeroCentre: 357, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -20', numeroCentre: 358, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -21', numeroCentre: 359, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -22', numeroCentre: 360, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -23', numeroCentre: 361, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -24', numeroCentre: 362, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -25', numeroCentre: 363, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', nomBureau: 'CES FUKUZAWA I -26', numeroCentre: 364, votants: 418),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -1', numeroCentre: 365, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -2', numeroCentre: 366, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -3', numeroCentre: 367, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -4', numeroCentre: 368, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -5', numeroCentre: 369, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -6', numeroCentre: 370, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -7', numeroCentre: 371, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -8', numeroCentre: 372, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -9', numeroCentre: 373, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -10', numeroCentre: 374, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -11', numeroCentre: 375, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -12', numeroCentre: 376, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -13', numeroCentre: 377, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -14', numeroCentre: 378, votants: 399),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', nomBureau: 'CEM BARWAQO I -15', numeroCentre: 379, votants: 406),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -1', numeroCentre: 380, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -2', numeroCentre: 381, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -3', numeroCentre: 382, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -4', numeroCentre: 383, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -5', numeroCentre: 384, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -6', numeroCentre: 385, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -7', numeroCentre: 386, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -8', numeroCentre: 387, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -9', numeroCentre: 388, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -10', numeroCentre: 389, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -11', numeroCentre: 390, votants: 388),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', nomBureau: 'ECOLE BARWAQO I -12', numeroCentre: 391, votants: 392),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -1', numeroCentre: 392, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -2', numeroCentre: 393, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -3', numeroCentre: 394, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -4', numeroCentre: 395, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -5', numeroCentre: 396, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -6', numeroCentre: 397, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -7', numeroCentre: 398, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -8', numeroCentre: 399, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -9', numeroCentre: 400, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -10', numeroCentre: 401, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -11', numeroCentre: 402, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -12', numeroCentre: 403, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -13', numeroCentre: 404, votants: 398),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', nomBureau: 'ECOLE TOUR-OUSBO I -14', numeroCentre: 405, votants: 407),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE HAYABLEY', nomBureau: 'ECOLE HAYABLEY 1', numeroCentre: 406, votants: 417),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE HAYABLEY', nomBureau: 'ECOLE HAYABLEY 2', numeroCentre: 407, votants: 417),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE HAYABLEY', nomBureau: 'ECOLE HAYABLEY 3', numeroCentre: 408, votants: 417),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE HAYABLEY', nomBureau: 'ECOLE HAYABLEY 4', numeroCentre: 409, votants: 417),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE HAYABLEY', nomBureau: 'ECOLE HAYABLEY 5', numeroCentre: 410, votants: 417),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE HAYABLEY', nomBureau: 'ECOLE HAYABLEY 6', numeroCentre: 411, votants: 417),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE HAYABLEY', nomBureau: 'ECOLE HAYABLEY 7', numeroCentre: 412, votants: 417),
    Bureau(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE HAYABLEY', nomBureau: 'ECOLE HAYABLEY 8', numeroCentre: 413, votants: 421),
  ];

  static const List<CentreSuivi> centresSuivi = [
    CentreSuivi(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'PREFECTURE DE DJIBOUTI', codeCentre: 1, nombreBureaux: 3, inscrits: 934, cumulRetraits: 191, restant: 743, pctRetrait: 0.204497, retraitsDailyData: const {'10/03/2026': 14, '11/03/2026': 14, '12/03/2026': 13, '13/03/2026': 13, '14/03/2026': 13, '15/03/2026': 13, '16/03/2026': 17, '17/03/2026': 25, '18/03/2026': 39, '19/03/2026': 30}),
    CentreSuivi(commune: 'RAS DIKA', arrondissement: 'Arrondissement du Plateau', nomCentre: 'ECOLE Z.P.S', codeCentre: 2, nombreBureaux: 12, inscrits: 4745, cumulRetraits: 1526, restant: 3219, pctRetrait: 0.321602, retraitsDailyData: const {'10/03/2026': 190, '11/03/2026': 190, '12/03/2026': 190, '13/03/2026': 190, '14/03/2026': 189, '15/03/2026': 189, '16/03/2026': 103, '17/03/2026': 164, '18/03/2026': 66, '19/03/2026': 55}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE HADJI-DIDEH', codeCentre: 3, nombreBureaux: 8, inscrits: 3065, cumulRetraits: 272, restant: 2793, pctRetrait: 0.088744, retraitsDailyData: const {'10/03/2026': 25, '11/03/2026': 24, '12/03/2026': 24, '13/03/2026': 24, '14/03/2026': 24, '15/03/2026': 24, '16/03/2026': 50, '17/03/2026': 41, '18/03/2026': 25, '19/03/2026': 11}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'PREMIER ARRONDT', codeCentre: 4, nombreBureaux: 5, inscrits: 1790, cumulRetraits: 156, restant: 1634, pctRetrait: 0.087151, retraitsDailyData: const {'10/03/2026': 14, '11/03/2026': 14, '12/03/2026': 14, '13/03/2026': 14, '14/03/2026': 14, '15/03/2026': 13, '16/03/2026': 22, '17/03/2026': 25, '18/03/2026': 16, '19/03/2026': 10}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CHARIA CENTRALE', codeCentre: 5, nombreBureaux: 4, inscrits: 1634, cumulRetraits: 165, restant: 1469, pctRetrait: 0.100979, retraitsDailyData: const {'10/03/2026': 15, '11/03/2026': 15, '12/03/2026': 15, '13/03/2026': 14, '14/03/2026': 14, '15/03/2026': 14, '16/03/2026': 23, '17/03/2026': 25, '18/03/2026': 18, '19/03/2026': 12}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 3', codeCentre: 6, nombreBureaux: 8, inscrits: 3021, cumulRetraits: 336, restant: 2685, pctRetrait: 0.111221, retraitsDailyData: const {'10/03/2026': 26, '11/03/2026': 26, '12/03/2026': 26, '13/03/2026': 26, '14/03/2026': 26, '15/03/2026': 25, '16/03/2026': 50, '17/03/2026': 48, '18/03/2026': 50, '19/03/2026': 33}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'CDC QUARTIER 4', codeCentre: 7, nombreBureaux: 8, inscrits: 3221, cumulRetraits: 247, restant: 2974, pctRetrait: 0.076684, retraitsDailyData: const {'10/03/2026': 20, '11/03/2026': 20, '12/03/2026': 20, '13/03/2026': 19, '14/03/2026': 19, '15/03/2026': 19, '16/03/2026': 35, '17/03/2026': 56, '18/03/2026': 24, '19/03/2026': 15}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'OFFICE VOIRIE DJIBOUTI', codeCentre: 8, nombreBureaux: 6, inscrits: 2441, cumulRetraits: 268, restant: 2173, pctRetrait: 0.109791, retraitsDailyData: const {'10/03/2026': 19, '11/03/2026': 19, '12/03/2026': 19, '13/03/2026': 19, '14/03/2026': 18, '15/03/2026': 18, '16/03/2026': 36, '17/03/2026': 35, '18/03/2026': 42, '19/03/2026': 43}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '1er Arrondissement', nomCentre: 'ECOLE EINGUELLA', codeCentre: 9, nombreBureaux: 15, inscrits: 5890, cumulRetraits: 622, restant: 5268, pctRetrait: 0.105603, retraitsDailyData: const {'10/03/2026': 59, '11/03/2026': 59, '12/03/2026': 59, '13/03/2026': 58, '14/03/2026': 58, '15/03/2026': 58, '16/03/2026': 91, '17/03/2026': 58, '18/03/2026': 86, '19/03/2026': 36}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE Q5', codeCentre: 10, nombreBureaux: 11, inscrits: 4376, cumulRetraits: 316, restant: 4060, pctRetrait: 0.072212, retraitsDailyData: const {'10/03/2026': 34, '11/03/2026': 34, '12/03/2026': 34, '13/03/2026': 34, '14/03/2026': 34, '15/03/2026': 34, '16/03/2026': 19, '17/03/2026': 16, '18/03/2026': 38, '19/03/2026': 39}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE CHATEAU D\'EAU', codeCentre: 11, nombreBureaux: 9, inscrits: 3419, cumulRetraits: 283, restant: 3136, pctRetrait: 0.082773, retraitsDailyData: const {'10/03/2026': 24, '11/03/2026': 24, '12/03/2026': 24, '13/03/2026': 24, '14/03/2026': 24, '15/03/2026': 23, '16/03/2026': 43, '17/03/2026': 28, '18/03/2026': 25, '19/03/2026': 44}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 6 BIS', codeCentre: 12, nombreBureaux: 11, inscrits: 4351, cumulRetraits: 412, restant: 3939, pctRetrait: 0.094691, retraitsDailyData: const {'10/03/2026': 38, '11/03/2026': 38, '12/03/2026': 38, '13/03/2026': 38, '14/03/2026': 38, '15/03/2026': 37, '16/03/2026': 70, '17/03/2026': 36, '18/03/2026': 36, '19/03/2026': 43}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE QUARTIER 7', codeCentre: 13, nombreBureaux: 14, inscrits: 5718, cumulRetraits: 408, restant: 5310, pctRetrait: 0.071354, retraitsDailyData: const {'10/03/2026': 33, '11/03/2026': 33, '12/03/2026': 33, '13/03/2026': 32, '14/03/2026': 32, '15/03/2026': 32, '16/03/2026': 50, '17/03/2026': 53, '18/03/2026': 48, '19/03/2026': 62}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GACHAMALEH', codeCentre: 14, nombreBureaux: 12, inscrits: 4709, cumulRetraits: 244, restant: 4465, pctRetrait: 0.051816, retraitsDailyData: const {'10/03/2026': 20, '11/03/2026': 20, '12/03/2026': 20, '13/03/2026': 19, '14/03/2026': 19, '15/03/2026': 19, '16/03/2026': 34, '17/03/2026': 31, '18/03/2026': 20, '19/03/2026': 42}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE GUELLEH BATAL', codeCentre: 15, nombreBureaux: 13, inscrits: 5125, cumulRetraits: 365, restant: 4760, pctRetrait: 0.071220, retraitsDailyData: const {'10/03/2026': 27, '11/03/2026': 27, '12/03/2026': 26, '13/03/2026': 26, '14/03/2026': 26, '15/03/2026': 26, '16/03/2026': 48, '17/03/2026': 40, '18/03/2026': 37, '19/03/2026': 82}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE ARHIBA', codeCentre: 16, nombreBureaux: 14, inscrits: 5506, cumulRetraits: 352, restant: 5154, pctRetrait: 0.063930, retraitsDailyData: const {'10/03/2026': 30, '11/03/2026': 30, '12/03/2026': 30, '13/03/2026': 29, '14/03/2026': 29, '15/03/2026': 29, '16/03/2026': 32, '17/03/2026': 46, '18/03/2026': 42, '19/03/2026': 55}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE AL-HOURIYA', codeCentre: 17, nombreBureaux: 10, inscrits: 3985, cumulRetraits: 242, restant: 3743, pctRetrait: 0.060728, retraitsDailyData: const {'10/03/2026': 15, '11/03/2026': 15, '12/03/2026': 15, '13/03/2026': 15, '14/03/2026': 15, '15/03/2026': 14, '16/03/2026': 24, '17/03/2026': 27, '18/03/2026': 39, '19/03/2026': 63}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'ECOLE DU STADE', codeCentre: 18, nombreBureaux: 7, inscrits: 2785, cumulRetraits: 160, restant: 2625, pctRetrait: 0.057451, retraitsDailyData: const {'10/03/2026': 16, '11/03/2026': 16, '12/03/2026': 15, '13/03/2026': 15, '14/03/2026': 15, '15/03/2026': 15, '16/03/2026': 17, '17/03/2026': 33, '18/03/2026': 2, '19/03/2026': 16}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '2ème arrondissement', nomCentre: 'CEM AMBOULI', codeCentre: 19, nombreBureaux: 13, inscrits: 5349, cumulRetraits: 376, restant: 4973, pctRetrait: 0.070294, retraitsDailyData: const {'10/03/2026': 26, '11/03/2026': 26, '12/03/2026': 26, '13/03/2026': 26, '14/03/2026': 26, '15/03/2026': 26, '16/03/2026': 24, '17/03/2026': 54, '18/03/2026': 88, '19/03/2026': 54}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI I', codeCentre: 20, nombreBureaux: 10, inscrits: 4093, cumulRetraits: 228, restant: 3865, pctRetrait: 0.055705, retraitsDailyData: const {'10/03/2026': 21, '11/03/2026': 20, '12/03/2026': 20, '13/03/2026': 20, '14/03/2026': 20, '15/03/2026': 20, '16/03/2026': 32, '17/03/2026': 29, '18/03/2026': 24, '19/03/2026': 22}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE AMBOULI II', codeCentre: 21, nombreBureaux: 15, inscrits: 5819, cumulRetraits: 259, restant: 5560, pctRetrait: 0.044509, retraitsDailyData: const {'10/03/2026': 20, '11/03/2026': 20, '12/03/2026': 20, '13/03/2026': 19, '14/03/2026': 19, '15/03/2026': 19, '16/03/2026': 27, '17/03/2026': 33, '18/03/2026': 42, '19/03/2026': 40}),
    CentreSuivi(commune: 'BOULAOS', arrondissement: '3ème arrondissement', nomCentre: 'ECOLE GABODE V', codeCentre: 22, nombreBureaux: 9, inscrits: 3367, cumulRetraits: 118, restant: 3249, pctRetrait: 0.035046, retraitsDailyData: const {'10/03/2026': 6, '11/03/2026': 6, '12/03/2026': 6, '13/03/2026': 6, '14/03/2026': 6, '15/03/2026': 6, '16/03/2026': 17, '17/03/2026': 20, '18/03/2026': 22, '19/03/2026': 23}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA I', codeCentre: 23, nombreBureaux: 12, inscrits: 4498, cumulRetraits: 568, restant: 3930, pctRetrait: 0.126278, retraitsDailyData: const {'10/03/2026': 20, '11/03/2026': 20, '12/03/2026': 20, '13/03/2026': 20, '14/03/2026': 19, '15/03/2026': 19, '16/03/2026': 55, '17/03/2026': 79, '18/03/2026': 162, '19/03/2026': 154}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PHARE', codeCentre: 24, nombreBureaux: 18, inscrits: 7245, cumulRetraits: 949, restant: 6296, pctRetrait: 0.130987, retraitsDailyData: const {'10/03/2026': 30, '11/03/2026': 30, '12/03/2026': 30, '13/03/2026': 30, '14/03/2026': 30, '15/03/2026': 30, '16/03/2026': 90, '17/03/2026': 112, '18/03/2026': 272, '19/03/2026': 295}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA II', codeCentre: 25, nombreBureaux: 10, inscrits: 3815, cumulRetraits: 502, restant: 3313, pctRetrait: 0.131586, retraitsDailyData: const {'10/03/2026': 23, '11/03/2026': 23, '12/03/2026': 23, '13/03/2026': 23, '14/03/2026': 23, '15/03/2026': 22, '16/03/2026': 57, '17/03/2026': 46, '18/03/2026': 135, '19/03/2026': 127}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'CEM HAYEL SAID', codeCentre: 26, nombreBureaux: 9, inscrits: 3634, cumulRetraits: 568, restant: 3066, pctRetrait: 0.156302, retraitsDailyData: const {'10/03/2026': 12, '11/03/2026': 11, '12/03/2026': 11, '13/03/2026': 11, '14/03/2026': 11, '15/03/2026': 11, '16/03/2026': 55, '17/03/2026': 74, '18/03/2026': 133, '19/03/2026': 239}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA III', codeCentre: 27, nombreBureaux: 8, inscrits: 3330, cumulRetraits: 404, restant: 2926, pctRetrait: 0.121321, retraitsDailyData: const {'10/03/2026': 17, '11/03/2026': 17, '12/03/2026': 17, '13/03/2026': 17, '14/03/2026': 17, '15/03/2026': 16, '16/03/2026': 37, '17/03/2026': 53, '18/03/2026': 117, '19/03/2026': 96}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII', codeCentre: 28, nombreBureaux: 11, inscrits: 4187, cumulRetraits: 483, restant: 3704, pctRetrait: 0.115357, retraitsDailyData: const {'10/03/2026': 17, '11/03/2026': 17, '12/03/2026': 17, '13/03/2026': 16, '14/03/2026': 16, '15/03/2026': 16, '16/03/2026': 64, '17/03/2026': 47, '18/03/2026': 135, '19/03/2026': 138}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE BALBALA VII BIS', codeCentre: 29, nombreBureaux: 9, inscrits: 3711, cumulRetraits: 425, restant: 3286, pctRetrait: 0.114524, retraitsDailyData: const {'10/03/2026': 13, '11/03/2026': 13, '12/03/2026': 13, '13/03/2026': 13, '14/03/2026': 13, '15/03/2026': 13, '16/03/2026': 68, '17/03/2026': 51, '18/03/2026': 110, '19/03/2026': 118}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 12', codeCentre: 30, nombreBureaux: 10, inscrits: 3789, cumulRetraits: 592, restant: 3197, pctRetrait: 0.156242, retraitsDailyData: const {'10/03/2026': 28, '11/03/2026': 28, '12/03/2026': 28, '13/03/2026': 27, '14/03/2026': 27, '15/03/2026': 27, '16/03/2026': 86, '17/03/2026': 63, '18/03/2026': 139, '19/03/2026': 139}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 14', codeCentre: 31, nombreBureaux: 9, inscrits: 3639, cumulRetraits: 535, restant: 3104, pctRetrait: 0.147018, retraitsDailyData: const {'10/03/2026': 22, '11/03/2026': 22, '12/03/2026': 22, '13/03/2026': 22, '14/03/2026': 21, '15/03/2026': 21, '16/03/2026': 75, '17/03/2026': 72, '18/03/2026': 124, '19/03/2026': 134}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE NITOBE', codeCentre: 32, nombreBureaux: 8, inscrits: 3075, cumulRetraits: 413, restant: 2662, pctRetrait: 0.134309, retraitsDailyData: const {'10/03/2026': 20, '11/03/2026': 20, '12/03/2026': 20, '13/03/2026': 20, '14/03/2026': 19, '15/03/2026': 19, '16/03/2026': 35, '17/03/2026': 39, '18/03/2026': 131, '19/03/2026': 90}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '4ème arrondissement', nomCentre: 'ECOLE PK 20', codeCentre: 33, nombreBureaux: 3, inscrits: 922, cumulRetraits: 165, restant: 757, pctRetrait: 0.178959, retraitsDailyData: const {'10/03/2026': 8, '11/03/2026': 7, '12/03/2026': 7, '13/03/2026': 7, '14/03/2026': 7, '15/03/2026': 7, '16/03/2026': 25, '17/03/2026': 20, '18/03/2026': 53, '19/03/2026': 24}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BALBALA VI', codeCentre: 34, nombreBureaux: 14, inscrits: 5504, cumulRetraits: 568, restant: 4936, pctRetrait: 0.103198, retraitsDailyData: const {'10/03/2026': 28, '11/03/2026': 28, '12/03/2026': 28, '13/03/2026': 28, '14/03/2026': 27, '15/03/2026': 27, '16/03/2026': 156, '17/03/2026': 79, '18/03/2026': 124, '19/03/2026': 43}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CES FUKUZAWA', codeCentre: 35, nombreBureaux: 26, inscrits: 10568, cumulRetraits: 983, restant: 9585, pctRetrait: 0.093017, retraitsDailyData: const {'10/03/2026': 67, '11/03/2026': 67, '12/03/2026': 66, '13/03/2026': 66, '14/03/2026': 66, '15/03/2026': 66, '16/03/2026': 60, '17/03/2026': 230, '18/03/2026': 195, '19/03/2026': 100}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'CEM BARWAQO', codeCentre: 36, nombreBureaux: 15, inscrits: 5992, cumulRetraits: 465, restant: 5527, pctRetrait: 0.077603, retraitsDailyData: const {'10/03/2026': 27, '11/03/2026': 27, '12/03/2026': 26, '13/03/2026': 26, '14/03/2026': 26, '15/03/2026': 26, '16/03/2026': 67, '17/03/2026': 76, '18/03/2026': 110, '19/03/2026': 54}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE BARWAQO', codeCentre: 37, nombreBureaux: 12, inscrits: 4660, cumulRetraits: 252, restant: 4408, pctRetrait: 0.054077, retraitsDailyData: const {'10/03/2026': 14, '11/03/2026': 14, '12/03/2026': 14, '13/03/2026': 14, '14/03/2026': 14, '15/03/2026': 14, '16/03/2026': 40, '17/03/2026': 33, '18/03/2026': 56, '19/03/2026': 39}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE TOUR-OUSBO', codeCentre: 38, nombreBureaux: 14, inscrits: 5581, cumulRetraits: 364, restant: 5217, pctRetrait: 0.065221, retraitsDailyData: const {'10/03/2026': 25, '11/03/2026': 25, '12/03/2026': 25, '13/03/2026': 25, '14/03/2026': 24, '15/03/2026': 24, '16/03/2026': 70, '17/03/2026': 36, '18/03/2026': 66, '19/03/2026': 44}),
    CentreSuivi(commune: 'BALBALA', arrondissement: '5ème arrondissement', nomCentre: 'ECOLE HAYABLEY', codeCentre: 39, nombreBureaux: 8, inscrits: 3340, cumulRetraits: 319, restant: 3021, pctRetrait: 0.095509, retraitsDailyData: const {'10/03/2026': 24, '11/03/2026': 24, '12/03/2026': 24, '13/03/2026': 24, '14/03/2026': 23, '15/03/2026': 23, '16/03/2026': 29, '17/03/2026': 36, '18/03/2026': 69, '19/03/2026': 43}),
  ];

  static const List<SyntheseArr> syntheseArr = [
    SyntheseArr(arrondissement: 'Arrondissement du Plateau', inscrits: 5679, retires: 1717, restant: 3962, pctRetrait: 0.302342),
    SyntheseArr(arrondissement: '1er Arrondissement', inscrits: 21062, retires: 2066, restant: 18996, pctRetrait: 0.098091),
    SyntheseArr(arrondissement: '2ème arrondissement', inscrits: 45323, retires: 3158, restant: 42165, pctRetrait: 0.069678),
    SyntheseArr(arrondissement: '3ème arrondissement', inscrits: 13279, retires: 605, restant: 12674, pctRetrait: 0.045561),
    SyntheseArr(arrondissement: '4ème arrondissement', inscrits: 41845, retires: 5604, restant: 36241, pctRetrait: 0.133923),
    SyntheseArr(arrondissement: '5ème arrondissement', inscrits: 35645, retires: 2951, restant: 32694, pctRetrait: 0.082789),
  ];

  static int get totalInscrits => 162833;
  static int get totalBureaux => 413;
  static int get totalCentres => 39;
  static int get totalRetires => 16101;
  static int get totalRestant => 146732;
  static double get pctRetraitNational => 0.098880;
  static String get dateMaj => '19/03/2026';
}